git-svn-id: http://svn.centreon.com/oreon-dev@1812 6bcd3966-0018-0410-8128-fd23d134de7e

diff --git a/ODS_SRC_ETC/ods b/ODS_SRC_ETC/ods
--- a/ODS_SRC_ETC/ods
+++ b/ODS_SRC_ETC/ods
@@ -40,6 +40,7 @@ killproc_ods ()
     fi    
     ODSPID=`head -n 1 $ODSRunFile`
     kill $ODSPID
+    rm -f $ODSRunFile
 }
 
 
@@ -69,12 +70,6 @@ if [ ! -f $ODSBin ]; then
     exit 1
 fi
 
-# Check lock file
-if [ ! -f $ODSRunFile ]; then
-    echo "Error : $ODSRunFile already Exists."
-    exit 1
-fi
-
 # Check that ods.cfg exists.
 if [ ! -f $ODSCfgFile ]; then
     echo "Configuration file $ODSCfgFile not found.  Exiting."
@@ -86,7 +81,12 @@ case "$1" in
 
     start)
 	echo "Starting ODS Collector : ods_daemon"
-	chown $NagiosUser:$NagiosGroup $ODSRunFile
+	#chown $NagiosUser:$NagiosGroup $ODSRunFile
+	# Check lock file
+	if test -f $ODSRunFile; then
+		echo "Error : $ODSRunFile already Exists."
+		exit 1
+	fi
 	su - $NagiosUser -c "$ODSBin &"
 	if [ -d $ODSLockDir ]; then touch $ODSLockDir/$ODSLockFile; fi
 			#sleep 1
@@ -118,8 +118,6 @@ case "$1" in
 	else
 	    echo ' done.'
 	fi
-	
-	rm -f $ODSRunFile $ODSLockDir/$ODSLockFile
 	;;
 
     status)
