Insert commands and decision to add user/group in FreeBSD

diff --git a/libinstall/functions b/libinstall/functions
--- a/libinstall/functions
+++ b/libinstall/functions
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/bash
 
 #----
 ## @Synopsis	This file contains functions to be used by Centreon install scripts
@@ -47,8 +47,8 @@ SETCOLOR_NORMAL="\\033[0;39m"
 ## @Globals	LOG_FILE
 #----
 function echo_info() {
-    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_INFO}${2}${SETCOLOR_NORMAL}" 
-    echo -e "$1 : $2" >> $LOG_FILE
+	echo -e "${1}${MOVE_TO_COL}${SETCOLOR_INFO}${2}${SETCOLOR_NORMAL}" 
+	echo -e "$1 : $2" >> $LOG_FILE
 }
 
 #----
@@ -56,8 +56,8 @@ function echo_info() {
 ## @param	string to trim
 ## @return	string
 #----
-function trim() {    
-    echo "$1" | sed 's/^[ \t]*\(.*\)[ \t]*$/\1/'
+function trim() {	
+	echo "$1" | sed 's/^[ \t]*\(.*\)[ \t]*$/\1/'
 }
 
 #----
@@ -69,8 +69,8 @@ function trim() {
 ## @Globals	LOG_FILE
 #----
 function echo_success() {
-    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_SUCCESS}${2}${SETCOLOR_NORMAL}" 
-    echo -e "$1 : $2" >> $LOG_FILE
+	echo -e "${1}${MOVE_TO_COL}${SETCOLOR_SUCCESS}${2}${SETCOLOR_NORMAL}" 
+	echo -e "$1 : $2" >> $LOG_FILE
 }
 
 #----
@@ -82,8 +82,8 @@ function echo_success() {
 ## @Globals	LOG_FILE
 #----
 function echo_failure() {
-    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_FAILURE}${2}${SETCOLOR_NORMAL}"
-    echo -e "$1 : $2" >> $LOG_FILE
+	echo -e "${1}${MOVE_TO_COL}${SETCOLOR_FAILURE}${2}${SETCOLOR_NORMAL}"
+	echo -e "$1 : $2" >> $LOG_FILE
 }
 
 #----
@@ -95,8 +95,8 @@ function echo_failure() {
 ## @Globals	LOG_FILE
 #----
 function echo_passed() {
-    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
-    echo -e "$1 : $2" >> $LOG_FILE
+	echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
+	echo -e "$1 : $2" >> $LOG_FILE
 }
 
 #----
@@ -108,8 +108,8 @@ function echo_passed() {
 ## @Globals	LOG_FILE
 #----
 function echo_warning() {
-    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
-    echo -e "$1 : $2" >> $LOG_FILE
+	echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
+	echo -e "$1 : $2" >> $LOG_FILE
 }
 
 #----
@@ -202,9 +202,9 @@ function define_specific_binary_vars() {
 ## make a question with yes/no possiblity
 ## use "no" response by default
 ## @param	message to print
-## @param 	default response (default to no)
-## @return 0 	yes
-## @return 1 	no
+## @param	 default response (default to no)
+## @return 0	 yes
+## @return 1	 no
 #----
 function yes_no_default() {
 	local message=$1
@@ -391,7 +391,11 @@ function answer_with_creategroup() {
 			grep "^$res:" /etc/group &>/dev/null && break;
 			yes_no_default "$(gettext "Do you want me to create this group ?") [$res]"
 			if [ $? -eq 0 ]; then
-				groupadd -r $res
+				if [ "$(uname -s)" = 'FreeBSD' ]; then
+					pw add group $res
+				else
+					groupadd -r $res
+				fi
 				if [ $? -ne 0 ]; then
 					echo_passed "$(gettext "Could not create group.")" "$critical"
 				fi
@@ -433,7 +437,11 @@ function answer_with_createuser() {
 			yes_no_default "$(gettext "Do you want me to create this user ?") [$res]"
 			if [ $? -eq 0 ]; then
 				group_id=$(grep "^$CENTREON_GROUP:" /etc/group | awk -F: '{ print $3 }')
-				useradd -r -c "Centreon User" -s /bin/bash -d "$CENTREON_VARLIB" -g $group_id $res
+				if [ "$(uname -s)" = "FreeBSD" ]; then
+					pw add user -s /usr/local/bin/bash -c "Centreon User" -d "$CENTREON_VARLIB" -g $CENTREON_GROUP -n $res
+				else
+					useradd -r -c "Centreon User" -s /bin/bash -d "$CENTREON_VARLIB" -g $group_id $res
+				fi
 				if [ $? -ne 0 ]; then
 					echo_passed "$(gettext "Could not create user")" "$critical"
 				fi
@@ -509,8 +517,8 @@ function answer_with_testuser_optional()
 ## Test if file exist
 ## @param	file
 ## @param	variable to reset
-## @return 0 	file exist
-## @return 1 	file does not exist
+## @return 0	 file exist
+## @return 1	 file does not exist
 #----
 function testfile_clean() {
 	local file="$1"
@@ -591,17 +599,17 @@ function select_in_array() {
 #----
 ## Define where is  plugins directory
 ## in last version of this script, you have been a possibility to create if not exist. now is not possible. You will create manualy.
-## @Globals     PLUGIN_DIR, DEFAULT_PLUGIN_DIR
+## @Globals	 PLUGIN_DIR, DEFAULT_PLUGIN_DIR
 #----
 function locate_plugindir() {
-        testdir_clean "$PLUGIN_DIR" "PLUGIN_DIR"
-        if [ -z "$PLUGIN_DIR" ] ; then
-                answer_with_testdir "$(gettext "Where is your monitoring plugins (libexec) directory ?")" "$DEFAULT_PLUGIN_DIR" "PLUGIN_DIR"
-                echo_success "$(gettext "Path" ) $PLUGIN_DIR" "$ok"
-        fi
-        PLUGIN_DIR=`trim ${PLUGIN_DIR%/}`
-        export PLUGIN_DIR
-        log "INFO" "PLUGIN_DIR: $PLUGIN_DIR"
+		testdir_clean "$PLUGIN_DIR" "PLUGIN_DIR"
+		if [ -z "$PLUGIN_DIR" ] ; then
+				answer_with_testdir "$(gettext "Where is your monitoring plugins (libexec) directory ?")" "$DEFAULT_PLUGIN_DIR" "PLUGIN_DIR"
+				echo_success "$(gettext "Path" ) $PLUGIN_DIR" "$ok"
+		fi
+		PLUGIN_DIR=`trim ${PLUGIN_DIR%/}`
+		export PLUGIN_DIR
+		log "INFO" "PLUGIN_DIR: $PLUGIN_DIR"
 }
 
 #----
@@ -1153,24 +1161,24 @@ function configureApache() {
 			echo "$(gettext "Finding Apache Centreon configuration file")"
 			echo_success "'$DIR_APACHE_CONF/centreon.conf' :" "$ok"
 			yes_no_default "$(gettext "Do you want to update Centreon Apache sub configuration file ?")"
-                        if [ "$?" -eq 0 ] ; then 
-                            write_config="1"
-                            cp -f $DIR_APACHE_CONF/centreon.conf $DIR_APACHE_CONF/centreon.conf-bak >> $LOG_FILE 2>&1
-                            echo_info "$(gettext "Backup Centreon Apache configuration completed")"
-                        fi
+						if [ "$?" -eq 0 ] ; then 
+							write_config="1"
+							cp -f $DIR_APACHE_CONF/centreon.conf $DIR_APACHE_CONF/centreon.conf-bak >> $LOG_FILE 2>&1
+							echo_info "$(gettext "Backup Centreon Apache configuration completed")"
+						fi
 		else 
 			yes_no_default "$(gettext "Do you want to add Centreon Apache sub configuration file ?")"
 			[ "$?" -eq 0 ] && write_config="1"
 		fi
 	else 
 		write_config="1"
-    	fi
+		fi
 	if [ "$write_config" -eq 1 ] ; then 
-                if [ "$upgrade" -eq 1 ] ; then
-                    cp -f $dir_conf/centreon.apache.conf $DIR_APACHE_CONF/centreon.conf.new >> $LOG_FILE 2>&1
-                else
-                    cp -f $dir_conf/centreon.apache.conf $DIR_APACHE_CONF/centreon.conf >> $LOG_FILE 2>&1
-                fi
+				if [ "$upgrade" -eq 1 ] ; then
+					cp -f $dir_conf/centreon.apache.conf $DIR_APACHE_CONF/centreon.conf.new >> $LOG_FILE 2>&1
+				else
+					cp -f $dir_conf/centreon.apache.conf $DIR_APACHE_CONF/centreon.conf >> $LOG_FILE 2>&1
+				fi
 		echo_success "$(gettext "Create") '$DIR_APACHE_CONF/centreon.conf'" "$ok"
 		echo_success "$(gettext "Configuring Apache")" "$ok"
 		# After finishing the configuration -> 
@@ -1188,7 +1196,7 @@ function configureApache() {
 
 #----
 ## Define apache service init script and ask to reload apache
-## @return 0 	Apache reload OK
+## @return 0	 Apache reload OK
 ## @return 1	Apache reload FAIL
 #----
 function reload_service_apache() {
@@ -1204,6 +1212,8 @@ function reload_service_apache() {
 		service="/usr/local/etc/rc.d/apache"
 	elif [ -x /usr/local/etc/rc.d/apache2 ]; then
 		service="/etc/init.d/apache2"
+	elif [ -x /usr/local/etc/rc.d/apache24 ]; then
+		service="/usr/local/etc/rc.d/apache24"
 	else
 		echo_warning "$(gettext "Unable to restart Apache server")" "$warning"
 		log "WARN" "$(gettext "Unable to restart Apache server")"
@@ -1234,22 +1244,38 @@ function prepare_apache_config() {
 
 	# if INSTALL_DIR_CENTREON not found, ask:
 	[ -z "$INSTALL_DIR_CENTREON" ] && locate_centreon_installdir
-	
+
 	# Prepare apache config
-	${CAT} << __EOT__ > $directory/centreon.apache.conf
+	if [ "$(apachectl -v | grep 2.4)" ]; then
+		${CAT} << __EOT__ > $directory/centreon.apache.conf
 ##
 ## Section add by Centreon Install Setup
 ##
-	
+
 Alias /centreon $INSTALL_DIR_CENTREON/www/
 <Directory "$INSTALL_DIR_CENTREON/www">
-    Options Indexes
-    AllowOverride AuthConfig Options
-    Order allow,deny
-    Allow from all
+ Options Indexes
+ AllowOverride AuthConfig Options
+ Require all granted
 </Directory>
 
 __EOT__
+	else
+		${CAT} << __EOT__ > $directory/centreon.apache.conf
+##
+## Section add by Centreon Install Setup
+##
+
+Alias /centreon $INSTALL_DIR_CENTREON/www/
+<Directory "$INSTALL_DIR_CENTREON/www">
+	Options Indexes
+	AllowOverride AuthConfig Options
+	Order allow,deny
+	Allow from all
+</Directory>
+
+__EOT__
+	fi
 
 	if [ -e $directory/centreon.apache.conf ] ; then 
 		return 0
@@ -1274,7 +1300,7 @@ __EOT__
 function prepare_sudo_config() {
 	local directory="$1"
 
-    	locate_sudo
+		locate_sudo
 	# Find Monitoring Engine Init Script
 	locate_monitoringengine_init_script "$(gettext "What is the Monitoring engine init.d script ?")" "NO_DEFAULT" "MONITORINGENGINE_INIT_SCRIPT"
 	# find nagios binary if not define
@@ -1288,7 +1314,7 @@ function prepare_sudo_config() {
 	${CAT} <<- __EOT__ > $directory/centreon.sudo
 	## BEGIN: CENTREON SUDO
 	#Add by CENTREON installation script
-	User_Alias      CENTREON=$WEB_USER,$CENTREON_USER
+	User_Alias	  CENTREON=$WEB_USER,$CENTREON_USER
 	Defaults:CENTREON !requiretty
 	# Monitoring engine Restart
 	CENTREON   ALL = NOPASSWD: $MONITORINGENGINE_INIT_SCRIPT* restart
@@ -1367,7 +1393,7 @@ function configureSUDO(){
 	echo -e "\n$line"
 	echo -e "\t$(gettext "Configure Sudo")"
 	echo -e "$line"
-    	local no_force_sudo="0"
+		local no_force_sudo="0"
 	local dir_conf="$1"
 	# Generate a sudo config in directory
 	prepare_sudo_config "$dir_conf"
@@ -1375,7 +1401,7 @@ function configureSUDO(){
 	# Try to detect old configuration
 	sudo=`${GREP} -e "CENTREON SUDO" $SUDO_FILE > /dev/null 2>&1 ; echo $?`
 	if [ $sudo -eq 1 ]; then
-    		echo_info "$(gettext "Your sudo is not configured")"
+			echo_info "$(gettext "Your sudo is not configured")"
 		
 		if [ "${FORCE_SUDO_CONF:-0}" -eq 1 ] ; then
 			no_force_sudo="0"
@@ -1481,7 +1507,7 @@ __EOT__
 	log "INFO" "$(gettext "Change right on") : $INSTALL_DIR_CENTREON_CONF"
 	${CHOWN} $WEB_USER:$WEB_GROUP $INSTALL_DIR_CENTREON_CONF >> $LOG_FILE 2>&1
 	echo_success "Create $INSTALL_DIR_CENTREON_CONF" "OK"
-	
+
 }
 
 #----
@@ -1691,7 +1717,7 @@ function check_nagios_init_script()
 	elif [ -x "$DEFAULT_NAGIOS_INIT_SCRIPT" ] ; then
 		NAGIOS_INIT_SCRIPT=$DEFAULT_NAGIOS_INIT_SCRIPT
 	else
-    		echo_passed "$(gettext "Not possible to find Nagios init script")" "$critical"
+			echo_passed "$(gettext "Not possible to find Nagios init script")" "$critical"
 		answer_with_testfile "$(gettext "Where is Nagios init script")" "NO_DEFAULT" "NAGIOS_INIT_SCRIPT"
 	fi
 	NAGIOS_INIT_SCRIPT=${NAGIOS_INIT_SCRIPT%/}
@@ -1712,8 +1738,12 @@ function check_httpd_directory()
 		elif [ -d /usr/local/apache2/conf ] ; then
 			DIR_APACHE="/usr/local/apache2/conf"
 			DIR_APACHE_CONF="/usr/local/apache2/conf"
+		elif [ -d /usr/local/etc/apache24 ] ; then
+			# add for freeBSD new ports with apache2.4
+			DIR_APACHE="/usr/local/etc/apache24"
+			DIR_APACHE_CONF="/usr/local/etc/apache24/Includes"
 		elif [ -d /etc/apache2 ] ; then
-			DIR_APACHE="/etc/apache2"			
+			DIR_APACHE="/etc/apache2"
 			DIR_APACHE_CONF="/etc/apache2/conf.d"
 			if [ ! -d "$DIR_APACHE_CONF" ] ; then
 				mkdir "$DIR_APACHE_CONF"
@@ -2006,10 +2036,10 @@ function install_init_service() {
 	elif [ "$OS" = "SUSE" ] ; then
 		chkconfig --add $service
 	elif [ "$OS" = "REDHAT" ] ; then
-    # Just for CentOS :p bug #1148
-    if [ -x /sbin/chkconfig ] ; then
-      /sbin/chkconfig --add $service
-    else
+	# Just for CentOS :p bug #1148
+	if [ -x /sbin/chkconfig ] ; then
+	  /sbin/chkconfig --add $service
+	else
 		 chkconfig --add $service
    fi
 	elif [ "$OS" = "FREEBSD" ] ; then
@@ -2050,7 +2080,7 @@ function find_OS() {
 			[ -e "/etc/SuSE-release" ] ; then
 			dist_found="SUSE"
 			log "INFO" "$(gettext "GNU/Linux Suse Distribution")"
-                elif [ "$lsb_release" = "openSUSE project" ] || \
+				elif [ "$lsb_release" = "openSUSE project" ] || \
 			[ -e "/etc/SuSE-release" ] ; then
 			dist_found="SUSE"
 			log "INFO" "$(gettext "GNU/openSUSE Distribution")"
@@ -2086,19 +2116,19 @@ function find_OS() {
 ## use this function to clean and exit centreon install
 ## This function use <@function purge_centreon_tmp_dir> function.
 ## TODO: Need to add fonctionnality 
-##      - delete install file
-##      - restore inital rigth
-##      - ...
+##	  - delete install file
+##	  - restore inital rigth
+##	  - ...
 #----
 function clean_and_exit() {
   local trap_sig=${1:-0}
   if [ $trap_sig -eq 0 ] ; then
-    echo -e "$(gettext "\nTrap interrupt, Centreon'll exit now and clean install")"
-    yes_no_default "$(gettext "Do you really want to quit Centreon install process ? ")" "$no"
-    if [ $? -eq 1 ] ; then 
-      echo "$(gettext "Continue...")"
-      return 1
-    fi
+	echo -e "$(gettext "\nTrap interrupt, Centreon'll exit now and clean install")"
+	yes_no_default "$(gettext "Do you really want to quit Centreon install process ? ")" "$no"
+	if [ $? -eq 1 ] ; then 
+	  echo "$(gettext "Continue...")"
+	  return 1
+	fi
   fi
 	log "EXIT" "$(gettext "Exit Centreon install")"
   [ -n "$SUDO_FILE" -a $upgrade -eq 0 ] && clean_sudo "$SUDO_FILE" 0
@@ -2131,7 +2161,7 @@ function check_tmp_disk_space() {
 
 #----
 ## Ask to remove all temporaries working directory
-## @param     silent option (silent)
+## @param	 silent option (silent)
 ## @return 0	remove done
 ## @return 1	don't remove (abort by user)
 ## @Globals	TMP_DIR, yes
@@ -2142,7 +2172,7 @@ function purge_centreon_tmp_dir() {
 	local rc="0"
 	while [ $not_clean -ne 0 ] ; do
 		if [ "$silent" != "silent" ] ; then
-  			yes_no_default "$(gettext "Do you want me to remove the centreon temporary working space to continue installation ?")" "$yes"
+			  yes_no_default "$(gettext "Do you want me to remove the centreon temporary working space to continue installation ?")" "$yes"
 			rc=$?
 		else
 			rc=0
@@ -2173,13 +2203,13 @@ function clean_sudo() {
 	local sudo_old="$1"
 	local validate="${2:-0}"
   if [ ! -d "$TMP_DIR" ] ; then
-    local sudo_clean="/tmp/sudo.clean"
+	local sudo_clean="/tmp/sudo.clean"
   else
 	  local sudo_clean="$TMP_DIR/sudo.clean"
   fi  
   
   if ! grep "CENTREON SUDO" $sudo_old &>/dev/null ; then 
-    return 1
+	return 1
   fi
 
 	${CAT} $sudo_old | \
@@ -2203,7 +2233,7 @@ function clean_sudo() {
 #----
 ## Find file with macro in directory.
 ## @param	macro (separate with comma)
-## @param 	directoty where to find
+## @param	 directoty where to find
 ## @param	sub directory to find
 ## @param	file to search (possible to use pattern)
 ## @param	variable where define a list of file (temporaty file)
@@ -2255,8 +2285,8 @@ function check_result() {
 ## @param	user name
 ## @param	group name
 ## @Globals	fail
-## @return 0 	 end
-## @return 1 	 fail
+## @return 0	  end
+## @return 1	  fail
 #----
 function add_group() {
 	local user=$1
@@ -2265,7 +2295,11 @@ function add_group() {
 		echo_failure "$(gettext "Add group $group to user $user")" "$fail"
 		return 1
 	fi
-	usermod -a -G $group $user &>/dev/null
+	if [ "$(uname -s)" = 'FreeBSD' ]; then
+		pw mod user -G $group -n $user &>/dev/null
+	else
+		usermod -a -G $group $user &>/dev/null
+	fi
 	local ret=$?
 	check_result $ret "$(gettext "Add group $group to user $user")"
 	return $ret
